project_id = "cabzhcbnxbnhjannbpxj"

[functions.generate-content]
verify_jwt = true

[functions.scrape-url]
verify_jwt = true

[functions.dataforseo-research]
verify_jwt = true

[functions.seo-content-analyzer]
verify_jwt = true

[functions.serp-tracker]
verify_jwt = true

[functions.competitor-analyzer]
verify_jwt = true

[functions.seo-ai-chat]
verify_jwt = true

[functions.job-worker]
verify_jwt = true

[functions.keyword-clustering]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false
