project_id = "cabzhcbnxbnhjannbpxj"

[functions.generate-content]
verify_jwt = false

[functions.keyword-clustering]
verify_jwt = false

[functions.scrape-url]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.serp-tracker]
verify_jwt = false

[functions.dataforseo-research]
verify_jwt = false

[functions.competitor-analyzer]
verify_jwt = false

[functions.seo-content-analyzer]
verify_jwt = false

[functions.seo-ai-chat]
verify_jwt = false

[functions.job-worker]
verify_jwt = false

[functions.serp-monitor]
verify_jwt = false

[functions.content-gap-analyzer]
verify_jwt = false

[functions.ranking-predictor]
verify_jwt = false

[functions.voice-search-optimizer]
verify_jwt = false

[functions.content-predictor]
verify_jwt = false

[functions.auto-seo-fixer]
verify_jwt = false

[functions.smart-calendar]
verify_jwt = false

[functions.link-scorer]
verify_jwt = false

[functions.multi-location-analyzer]
verify_jwt = false

[functions.revenue-analyzer]
verify_jwt = false

[functions.white-label-generator]
verify_jwt = false

[functions.cross-channel-analyzer]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.comprehensive-audit]
verify_jwt = false

[functions.fetch-gsc-data]
verify_jwt = false

[functions.fetch-ga4-data]
verify_jwt = false

[functions.keyword-opportunity-analyzer]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.dataforseo-proxy]
verify_jwt = false
